"""geo.py — deterministic ASCII/box-drawing diagram geometry.

Every diagram in the RFL-AE corpus is generated by column arithmetic, never
hand-typed. This module is the single source of that arithmetic.

The core invariant: **all positions are absolute columns.** Helpers compose
because they share one coordinate space, not because they know about each
other.

Two rules that were learned the hard way and are enforced here:

1. `row()` RAISES on overlap. The original implementation used
   ``out.ljust(col) + text``, which silently concatenates when a computed
   start column falls inside text already emitted. That produced the corrupt
   line ``acceptquarantine`` and reported success. Overlap is now a hard error.
2. `hjoin()` takes ``(col, segment)`` — column first. Reversing the arguments
   raises ``TypeError: '<' not supported between instances of 'str' and 'int'``.

Typical use:

    from geo import cen, row, marks, bar, box, flow, dchain

    C = 25
    out = [row([("Migration Unit", C)])]
    out.append(marks([(C, "|")]))
    out += flow(C)                      # emits the vertical then the arrowhead
    out.append(row([("Independent Verifier", C)]))
    print("\\n".join(out))
"""

from __future__ import annotations

from typing import Iterable, List, Sequence, Tuple

__all__ = [
    "cen", "row", "marks", "bar", "hjoin", "bw", "box", "colbox", "flow",
    "boxfix", "dchain", "align", "padc", "tree",
]

# Box-drawing glyphs. The vertical bar is U+2502, NOT the ASCII pipe "|".
# Substituting ASCII for box-drawing glyphs is a recurring defect; the audit
# script's orphan/width checks assume these codepoints.
VERT = "\u2502"          # │
DOWN = "\u25bc"          # ▼
CORNER_TL = "\u250c"     # ┌
CORNER_TR = "\u2510"     # ┐
CORNER_BL = "\u2514"     # └
CORNER_BR = "\u2518"     # ┘
TEE_D = "\u252c"         # ┬
TEE_U = "\u2534"         # ┴
CROSS = "\u253c"         # ┼
HORIZ = "\u2500"         # ─


def cen(w: int, c: int) -> int:
    """Start column that centres a string of width `w` on absolute column `c`.

    Integer division means an even-width string lands one column left of true
    centre. This is intentional and consistent across every diagram: the audit
    script tolerates a 1-column offset, so do not "fix" individual diagrams.
    """
    return c - len(w) // 2 if isinstance(w, str) else c - w // 2


def _spans(cells: Sequence[Tuple[str, int]]) -> List[Tuple[int, int, str]]:
    out = []
    for text, col in cells:
        start = cen(text, col)
        if start < 0:
            raise ValueError(f"negative start col {start} for {text!r} at col {col}")
        out.append((start, start + len(text), text))
    out.sort()
    for (s0, e0, t0), (s1, _e1, t1) in zip(out, out[1:]):
        if e0 > s1:
            raise ValueError(
                f"OVERLAP: {t0!r} ends at {e0} but {t1!r} starts at {s1}; "
                f"widen the column constants"
            )
    return out


def row(cells: Sequence[Tuple[str, int]]) -> str:
    """Place `(text, centre_column)` pairs on one line. Raises on overlap."""
    out = ""
    for start, _end, text in _spans(cells):
        out = out.ljust(start) + text
    return out


def marks(glyphs: Sequence[Tuple[int, str]]) -> str:
    """Place single glyphs at absolute columns: ``marks([(10, VERT)])``.

    The FIRST glyph must be preceded by ``col`` spaces -- dropping that pad
    renders every border at column 0 and silently destroys the layout.
    """
    out = ""
    prev = None
    for col, ch in sorted(glyphs):
        out = (" " * col + ch) if prev is None else out + " " * (col - prev - 1) + ch
        prev = col
    return out


def bar(glyphs: Sequence[Tuple[int, str]], ch: str = HORIZ) -> str:
    """Like `marks` but fills the gaps with `ch`. Used for box borders and fans.

    ``bar([(5, CORNER_TL), (25, TEE_D), (45, CORNER_TR)])`` draws a fan top.
    """
    out = ""
    prev = None
    for col, gl in sorted(glyphs):
        out = (" " * col + gl) if prev is None else out + ch * (col - prev - 1) + gl
        prev = col
    return out


def hjoin(segments: Sequence[Tuple[int, str]]) -> str:
    """Compose pre-rendered line fragments at absolute columns.

    Argument order is **(column, segment)**. Overlap raises rather than
    truncating, which is what lets multi-box composition work.
    """
    out = ""
    for col, seg in segments:
        if col < len(out):
            raise ValueError(f"overlap at col {col}: {out!r} + {seg!r}")
        out = out.ljust(col) + seg
    return out


def bw(lines: Sequence[str]) -> int:
    """Box width for content `lines`: widest line + 4 (two borders, two pads)."""
    return max(len(l) for l in lines) + 4


def box(lines: Sequence[str], C: int, tee: bool = True) -> Tuple[List[str], int, int]:
    """Render a bordered box centred on column `C`.

    Returns ``(rows, left_col, right_col)`` so callers can hang spines and
    sibling boxes off the actual border columns instead of re-deriving them.
    """
    w = bw(lines)
    left = C - w // 2
    right = left + w - 1
    out = [bar([(left, CORNER_TL), (right, CORNER_TR)])]
    for l in lines:
        out.append(hjoin([(left, VERT + " " + l.ljust(w - 4) + " " + VERT)]))
    tail = bar([(left, CORNER_BL), (C, TEE_D), (right, CORNER_BR)]) if tee \
        else bar([(left, CORNER_BL), (right, CORNER_BR)])
    out.append(tail)
    return out, left, right


def boxfix(lines: Sequence[str], C: int, G: int, center: bool = True) -> List[str]:
    """Box with a forced interior gutter of `G`, wider than `bw()` would give.

    Needed when a box must line up with a spine that is wider than its text.

    Geometry: each line is padded to exactly `G`, so the content row is
    ``VERT + " " + padc(text, G) + " " + VERT`` = G+4 characters. Relative to
    the left border the right border therefore sits at **G + 3** (because
    ``bw()`` = G + 4 and the border index is width - 1).

    A box built directly as ``VERT + " " + text.ljust(G-1) + VERT`` is a
    different construction: it is G+2 characters and its right border sits at
    **G + 1**. Do not mix the two formulas up -- conflating them is a known
    off-by-one defect.
    """
    padded = [padc(l, G) if center else l.ljust(G) for l in lines]
    return box(padded, C, tee=True)[0]


def colbox(lines: Sequence[Sequence[str]], cols: Sequence[int]) -> List[str]:
    """Render several boxes side by side, each centred on its own column."""
    boxes = [box(l, c, tee=False)[0] for l, c in zip(lines, cols)]
    lefts = [c - bw(l) // 2 for l, c in zip(lines, cols)]
    height = max(len(b) for b in boxes)
    out = []
    for i in range(height):
        segs = [(L, b[i][L:]) for b, L in zip(boxes, lefts) if i < len(b)]
        out.append(hjoin(segs))
    return out


def flow(C: int) -> List[str]:
    """The two-row spine continuation: a vertical bar then an arrowhead."""
    return [marks([(C, VERT)]), marks([(C, DOWN)])]


def dchain(items: Sequence[str], c: int = 4, g: str = "\u2193") -> List[str]:
    """Vertical chain joined by `g` (default '↓') indented to column `c`."""
    out = [items[0]]
    for it in items[1:]:
        out += [" " * c + g, it]
    return out


def padc(s: str, w: int) -> str:
    """Pad `s` to width `w`, centred."""
    d = w - len(s)
    return " " * (d // 2) + s + " " * (d - d // 2)


def align(pairs: Sequence[Tuple[str, str]], gap: int = 2) -> List[str]:
    """Two-column alignment from the widest left-hand label."""
    w = max(len(a) for a, _ in pairs)
    return [a.ljust(w) + " " * gap + b for a, b in pairs]


def tree(name: str, kids: Sequence[str], indent: str = "  ") -> List[str]:
    """A `name` root with `├──`/`└──` children (last child gets the corner)."""
    out = [name, indent + VERT]
    for i, k in enumerate(kids):
        out.append(indent + ("\u2514\u2500\u2500 " if i == len(kids) - 1
                             else "\u251c\u2500\u2500 ") + k)
    return out
